apiVersion: 1

datasources:
  - name: QuestDB
    type: postgres
    access: proxy
    url: questdb:8812
    database: qdb
    user: admin
    secureJsonData:
      password: quest
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: false
      database: 'qdb'
    editable: true
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
